default['caddy']['features'] = []
default['caddy']['email'] = nil
default['caddy']['hosts'] = {}
default['caddy']['ulimit'] = 8192
default['caddy']['ark']['url'] = "https://caddyserver.com/download/build?os=linux&arch=amd64&features=#{node['caddy']['features'].join(',')}"
default['caddy']['ark']['extension'] = 'tar.gz'
default['caddy']['ark']['binary_name'] = 'caddy'
default['caddy']['ark']['binaries'] = ["./#{node['caddy']['ark']['binary_name']}"]
default['caddy']['ark']['strip_components'] = 0
